<?php
/**
 * @file
 * Contains powrphotofilter.module.
 */
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function powrphotofilter_theme() {
    global $base_url;
    return [
        'powrphotofilter_config_popup' => [
            'template'  => 'powrphotofilter_config_popup',
            'render element' => 'dialog'
        ],
    ];
}

function powrphotofilter_page_top(array &$page_top) {
    if (isset($_COOKIE['powrphotofilter-installed'])) {
        global $base_url;
        unset($_COOKIE['powrphotofilter-installed']);
        setcookie('powrphotofilter-installed', null, -1, '/');
        $response = new RedirectResponse(Url::fromRoute('system.admin_config_content')->toString().'/formats/?powrphotofilter-installed');
        $response->send();
    }
}

/**
 * Implements hook_form_alter().
 */
function powrphotofilter_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    if (isset($_GET['powrphotofilter-installed'])) {
        $form['powrphotofilter_config_popup'] = [
            '#theme' => 'powrphotofilter_config_popup',
        ];
        $form["#attached"]["library"][] = 'powrphotofilter/dialog';
    }
}
