<?php
/**
 * @file
 * Contains powrimageslider.module.
 */
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function powrimageslider_theme() {
    global $base_url;
    return [
        'powrimageslider_config_popup' => [
            'template'  => 'powrimageslider_config_popup',
            'render element' => 'dialog'
        ],
    ];
}

function powrimageslider_page_top(array &$page_top) {
    if (isset($_COOKIE['powrimageslider-installed'])) {
        global $base_url;
        unset($_COOKIE['powrimageslider-installed']);
        setcookie('powrimageslider-installed', null, -1, '/');
        $response = new RedirectResponse(Url::fromRoute('system.admin_config_content')->toString().'/formats/?powrimageslider-installed');
        $response->send();
    }
}

/**
 * Implements hook_form_alter().
 */
function powrimageslider_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    if (isset($_GET['powrimageslider-installed'])) {
        $form['powrimageslider_config_popup'] = [
            '#theme' => 'powrimageslider_config_popup',
        ];
        $form["#attached"]["library"][] = 'powrimageslider/dialog';
    }
}
