<?php
/**
 * @file
 * Contains powrpack.module.
 */
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function powrpack_theme() {
    global $base_url;
    return [
        'powrpack_config_popup' => [
            'template'  => 'powrpack_config_popup',
            'render element' => 'dialog'
        ],
    ];
}

function powrpack_page_top(array &$page_top) {
    if (isset($_COOKIE['powrpack-installed'])) {
        global $base_url;
        unset($_COOKIE['powrpack-installed']);
        setcookie('powrpack-installed', null, -1, '/');
        $response = new RedirectResponse(Url::fromRoute('system.admin_config_content')->toString().'/formats/?powrpack-installed');
        $response->send();
    }
}

/**
 * Implements hook_form_alter().
 */
function powrpack_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    if (isset($_GET['powrpack-installed'])) {
        $form['powrpack_config_popup'] = [
            '#theme' => 'powrpack_config_popup',
        ];
        $form["#attached"]["library"][] = 'powrpack/dialog';
    }
}
