<?php
/**
 * @file
 * Contains powrmultislider.module.
 */
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function powrmultislider_theme() {
    global $base_url;
    return [
        'powrmultislider_config_popup' => [
            'template'  => 'powrmultislider_config_popup',
            'render element' => 'dialog'
        ],
    ];
}

function powrmultislider_page_top(array &$page_top) {
    if (isset($_COOKIE['powrmultislider-installed'])) {
        global $base_url;
        unset($_COOKIE['powrmultislider-installed']);
        setcookie('powrmultislider-installed', null, -1, '/');
        $response = new RedirectResponse(Url::fromRoute('system.admin_config_content')->toString().'/formats/?powrmultislider-installed');
        $response->send();
    }
}

/**
 * Implements hook_form_alter().
 */
function powrmultislider_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    if (isset($_GET['powrmultislider-installed'])) {
        $form['powrmultislider_config_popup'] = [
            '#theme' => 'powrmultislider_config_popup',
        ];
        $form["#attached"]["library"][] = 'powrmultislider/dialog';
    }
}
