<?php
/**
 * @file
 * Contains powrformbuilder.module.
 */
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function powrformbuilder_theme() {
    global $base_url;
    return [
        'powrformbuilder_config_popup' => [
            'template'  => 'powrformbuilder_config_popup',
            'render element' => 'dialog'
        ],
    ];
}

function powrformbuilder_page_top(array &$page_top) {
    if (isset($_COOKIE['powrformbuilder-installed'])) {
        global $base_url;
        unset($_COOKIE['powrformbuilder-installed']);
        setcookie('powrformbuilder-installed', null, -1, '/');
        $response = new RedirectResponse(Url::fromRoute('system.admin_config_content')->toString().'/formats/?powrformbuilder-installed');
        $response->send();
    }
}

/**
 * Implements hook_form_alter().
 */
function powrformbuilder_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    if (isset($_GET['powrformbuilder-installed'])) {
        $form['powrformbuilder_config_popup'] = [
            '#theme' => 'powrformbuilder_config_popup',
        ];
        $form["#attached"]["library"][] = 'powrformbuilder/dialog';
    }
}
