<?php
/**
 * @file
 * Contains powryoutubegallery.module.
 */
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function powryoutubegallery_theme() {
    global $base_url;
    return [
        'powryoutubegallery_config_popup' => [
            'template'  => 'powryoutubegallery_config_popup',
            'render element' => 'dialog'
        ],
    ];
}

function powryoutubegallery_page_top(array &$page_top) {
    if (isset($_COOKIE['powryoutubegallery-installed'])) {
        global $base_url;
        unset($_COOKIE['powryoutubegallery-installed']);
        setcookie('powryoutubegallery-installed', null, -1, '/');
        $response = new RedirectResponse(Url::fromRoute('system.admin_config_content')->toString().'/formats/?powryoutubegallery-installed');
        $response->send();
    }
}

/**
 * Implements hook_form_alter().
 */
function powryoutubegallery_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    if (isset($_GET['powryoutubegallery-installed'])) {
        $form['powryoutubegallery_config_popup'] = [
            '#theme' => 'powryoutubegallery_config_popup',
        ];
        $form["#attached"]["library"][] = 'powryoutubegallery/dialog';
    }
}
