<?php
/**
 * @file
 * Contains powrsalespop.module.
 */
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function powrsalespop_theme() {
    global $base_url;
    return [
        'powrsalespop_config_popup' => [
            'template'  => 'powrsalespop_config_popup',
            'render element' => 'dialog'
        ],
    ];
}

function powrsalespop_page_top(array &$page_top) {
    if (isset($_COOKIE['powrsalespop-installed'])) {
        global $base_url;
        unset($_COOKIE['powrsalespop-installed']);
        setcookie('powrsalespop-installed', null, -1, '/');
        $response = new RedirectResponse(Url::fromRoute('system.admin_config_content')->toString().'/formats/?powrsalespop-installed');
        $response->send();
    }
}

/**
 * Implements hook_form_alter().
 */
function powrsalespop_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    if (isset($_GET['powrsalespop-installed'])) {
        $form['powrsalespop_config_popup'] = [
            '#theme' => 'powrsalespop_config_popup',
        ];
        $form["#attached"]["library"][] = 'powrsalespop/dialog';
    }
}
