<?php
/**
 * @file
 * Contains powrmailinglist.module.
 */
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function powrmailinglist_theme() {
    global $base_url;
    return [
        'powrmailinglist_config_popup' => [
            'template'  => 'powrmailinglist_config_popup',
            'render element' => 'dialog'
        ],
    ];
}

function powrmailinglist_page_top(array &$page_top) {
    if (isset($_COOKIE['powrmailinglist-installed'])) {
        global $base_url;
        unset($_COOKIE['powrmailinglist-installed']);
        setcookie('powrmailinglist-installed', null, -1, '/');
        $response = new RedirectResponse(Url::fromRoute('system.admin_config_content')->toString().'/formats/?powrmailinglist-installed');
        $response->send();
    }
}

/**
 * Implements hook_form_alter().
 */
function powrmailinglist_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    if (isset($_GET['powrmailinglist-installed'])) {
        $form['powrmailinglist_config_popup'] = [
            '#theme' => 'powrmailinglist_config_popup',
        ];
        $form["#attached"]["library"][] = 'powrmailinglist/dialog';
    }
}
