<?php
/**
 * @file
 * Contains powrphotoeditor.module.
 */
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function powrphotoeditor_theme() {
    global $base_url;
    return [
        'powrphotoeditor_config_popup' => [
            'template'  => 'powrphotoeditor_config_popup',
            'render element' => 'dialog'
        ],
    ];
}

function powrphotoeditor_page_top(array &$page_top) {
    if (isset($_COOKIE['powrphotoeditor-installed'])) {
        global $base_url;
        unset($_COOKIE['powrphotoeditor-installed']);
        setcookie('powrphotoeditor-installed', null, -1, '/');
        $response = new RedirectResponse(Url::fromRoute('system.admin_config_content')->toString().'/formats/?powrphotoeditor-installed');
        $response->send();
    }
}

/**
 * Implements hook_form_alter().
 */
function powrphotoeditor_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    if (isset($_GET['powrphotoeditor-installed'])) {
        $form['powrphotoeditor_config_popup'] = [
            '#theme' => 'powrphotoeditor_config_popup',
        ];
        $form["#attached"]["library"][] = 'powrphotoeditor/dialog';
    }
}
