<?php
/**
 * @file
 * Contains powrmenu.module.
 */
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function powrmenu_theme() {
    global $base_url;
    return [
        'powrmenu_config_popup' => [
            'template'  => 'powrmenu_config_popup',
            'render element' => 'dialog'
        ],
    ];
}

function powrmenu_page_top(array &$page_top) {
    if (isset($_COOKIE['powrmenu-installed'])) {
        global $base_url;
        unset($_COOKIE['powrmenu-installed']);
        setcookie('powrmenu-installed', null, -1, '/');
        $response = new RedirectResponse(Url::fromRoute('system.admin_config_content')->toString().'/formats/?powrmenu-installed');
        $response->send();
    }
}

/**
 * Implements hook_form_alter().
 */
function powrmenu_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    if (isset($_GET['powrmenu-installed'])) {
        $form['powrmenu_config_popup'] = [
            '#theme' => 'powrmenu_config_popup',
        ];
        $form["#attached"]["library"][] = 'powrmenu/dialog';
    }
}
