<?php
/**
 * @file
 * Contains powrrssfeed.module.
 */
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function powrrssfeed_theme() {
    global $base_url;
    return [
        'powrrssfeed_config_popup' => [
            'template'  => 'powrrssfeed_config_popup',
            'render element' => 'dialog'
        ],
    ];
}

function powrrssfeed_page_top(array &$page_top) {
    if (isset($_COOKIE['powrrssfeed-installed'])) {
        global $base_url;
        unset($_COOKIE['powrrssfeed-installed']);
        setcookie('powrrssfeed-installed', null, -1, '/');
        $response = new RedirectResponse(Url::fromRoute('system.admin_config_content')->toString().'/formats/?powrrssfeed-installed');
        $response->send();
    }
}

/**
 * Implements hook_form_alter().
 */
function powrrssfeed_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    if (isset($_GET['powrrssfeed-installed'])) {
        $form['powrrssfeed_config_popup'] = [
            '#theme' => 'powrrssfeed_config_popup',
        ];
        $form["#attached"]["library"][] = 'powrrssfeed/dialog';
    }
}
