<?php
/**
 * @file
 * Contains powraboutus.module.
 */
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function powraboutus_theme() {
    global $base_url;
    return [
        'powraboutus_config_popup' => [
            'template'  => 'powraboutus_config_popup',
            'render element' => 'dialog'
        ],
    ];
}

function powraboutus_page_top(array &$page_top) {
    if (isset($_COOKIE['powraboutus-installed'])) {
        global $base_url;
        unset($_COOKIE['powraboutus-installed']);
        setcookie('powraboutus-installed', null, -1, '/');
        $response = new RedirectResponse(Url::fromRoute('system.admin_config_content')->toString().'/formats/?powraboutus-installed');
        $response->send();
    }
}

/**
 * Implements hook_form_alter().
 */
function powraboutus_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    if (isset($_GET['powraboutus-installed'])) {
        $form['powraboutus_config_popup'] = [
            '#theme' => 'powraboutus_config_popup',
        ];
        $form["#attached"]["library"][] = 'powraboutus/dialog';
    }
}
