<?php
/**
 * @file
 * Contains powrweeblystaging.module.
 */
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function powrweeblystaging_theme() {
    global $base_url;
    return [
        'powrweeblystaging_config_popup' => [
            'template'  => 'powrweeblystaging_config_popup',
            'render element' => 'dialog'
        ],
    ];
}

function powrweeblystaging_page_top(array &$page_top) {
    if (isset($_COOKIE['powrweeblystaging-installed'])) {
        global $base_url;
        unset($_COOKIE['powrweeblystaging-installed']);
        setcookie('powrweeblystaging-installed', null, -1, '/');
        $response = new RedirectResponse(Url::fromRoute('system.admin_config_content')->toString().'/formats/?powrweeblystaging-installed');
        $response->send();
    }
}

/**
 * Implements hook_form_alter().
 */
function powrweeblystaging_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    if (isset($_GET['powrweeblystaging-installed'])) {
        $form['powrweeblystaging_config_popup'] = [
            '#theme' => 'powrweeblystaging_config_popup',
        ];
        $form["#attached"]["library"][] = 'powrweeblystaging/dialog';
    }
}
