<?php
/**
 * @file
 * Contains powrreviews.module.
 */
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function powrreviews_theme() {
    global $base_url;
    return [
        'powrreviews_config_popup' => [
            'template'  => 'powrreviews_config_popup',
            'render element' => 'dialog'
        ],
    ];
}

function powrreviews_page_top(array &$page_top) {
    if (isset($_COOKIE['powrreviews-installed'])) {
        global $base_url;
        unset($_COOKIE['powrreviews-installed']);
        setcookie('powrreviews-installed', null, -1, '/');
        $response = new RedirectResponse(Url::fromRoute('system.admin_config_content')->toString().'/formats/?powrreviews-installed');
        $response->send();
    }
}

/**
 * Implements hook_form_alter().
 */
function powrreviews_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    if (isset($_GET['powrreviews-installed'])) {
        $form['powrreviews_config_popup'] = [
            '#theme' => 'powrreviews_config_popup',
        ];
        $form["#attached"]["library"][] = 'powrreviews/dialog';
    }
}
