<?php
/**
 * @file
 * Contains powrcountuptimer.module.
 */
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function powrcountuptimer_theme() {
    global $base_url;
    return [
        'powrcountuptimer_config_popup' => [
            'template'  => 'powrcountuptimer_config_popup',
            'render element' => 'dialog'
        ],
    ];
}

function powrcountuptimer_page_top(array &$page_top) {
    if (isset($_COOKIE['powrcountuptimer-installed'])) {
        global $base_url;
        unset($_COOKIE['powrcountuptimer-installed']);
        setcookie('powrcountuptimer-installed', null, -1, '/');
        $response = new RedirectResponse(Url::fromRoute('system.admin_config_content')->toString().'/formats/?powrcountuptimer-installed');
        $response->send();
    }
}

/**
 * Implements hook_form_alter().
 */
function powrcountuptimer_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    if (isset($_GET['powrcountuptimer-installed'])) {
        $form['powrcountuptimer_config_popup'] = [
            '#theme' => 'powrcountuptimer_config_popup',
        ];
        $form["#attached"]["library"][] = 'powrcountuptimer/dialog';
    }
}
