<?php
/**
 * @file
 * Contains powrbannerslider.module.
 */
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function powrbannerslider_theme() {
    global $base_url;
    return [
        'powrbannerslider_config_popup' => [
            'template'  => 'powrbannerslider_config_popup',
            'render element' => 'dialog'
        ],
    ];
}

function powrbannerslider_page_top(array &$page_top) {
    if (isset($_COOKIE['powrbannerslider-installed'])) {
        global $base_url;
        unset($_COOKIE['powrbannerslider-installed']);
        setcookie('powrbannerslider-installed', null, -1, '/');
        $response = new RedirectResponse(Url::fromRoute('system.admin_config_content')->toString().'/formats/?powrbannerslider-installed');
        $response->send();
    }
}

/**
 * Implements hook_form_alter().
 */
function powrbannerslider_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    if (isset($_GET['powrbannerslider-installed'])) {
        $form['powrbannerslider_config_popup'] = [
            '#theme' => 'powrbannerslider_config_popup',
        ];
        $form["#attached"]["library"][] = 'powrbannerslider/dialog';
    }
}
