<?php
/**
 * @file
 * Contains powrplancomparison.module.
 */
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function powrplancomparison_theme() {
    global $base_url;
    return [
        'powrplancomparison_config_popup' => [
            'template'  => 'powrplancomparison_config_popup',
            'render element' => 'dialog'
        ],
    ];
}

function powrplancomparison_page_top(array &$page_top) {
    if (isset($_COOKIE['powrplancomparison-installed'])) {
        global $base_url;
        unset($_COOKIE['powrplancomparison-installed']);
        setcookie('powrplancomparison-installed', null, -1, '/');
        $response = new RedirectResponse(Url::fromRoute('system.admin_config_content')->toString().'/formats/?powrplancomparison-installed');
        $response->send();
    }
}

/**
 * Implements hook_form_alter().
 */
function powrplancomparison_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    if (isset($_GET['powrplancomparison-installed'])) {
        $form['powrplancomparison_config_popup'] = [
            '#theme' => 'powrplancomparison_config_popup',
        ];
        $form["#attached"]["library"][] = 'powrplancomparison/dialog';
    }
}
