<?php
/**
 * @file
 * Contains powrlist.module.
 */
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function powrlist_theme() {
    global $base_url;
    return [
        'powrlist_config_popup' => [
            'template'  => 'powrlist_config_popup',
            'render element' => 'dialog'
        ],
    ];
}

function powrlist_page_top(array &$page_top) {
    if (isset($_COOKIE['powrlist-installed'])) {
        global $base_url;
        unset($_COOKIE['powrlist-installed']);
        setcookie('powrlist-installed', null, -1, '/');
        $response = new RedirectResponse(Url::fromRoute('system.admin_config_content')->toString().'/formats/?powrlist-installed');
        $response->send();
    }
}

/**
 * Implements hook_form_alter().
 */
function powrlist_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    if (isset($_GET['powrlist-installed'])) {
        $form['powrlist_config_popup'] = [
            '#theme' => 'powrlist_config_popup',
        ];
        $form["#attached"]["library"][] = 'powrlist/dialog';
    }
}
