<?php
/**
 * @file
 * Contains powrecommerce.module.
 */
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function powrecommerce_theme() {
    global $base_url;
    return [
        'powrecommerce_config_popup' => [
            'template'  => 'powrecommerce_config_popup',
            'render element' => 'dialog'
        ],
    ];
}

function powrecommerce_page_top(array &$page_top) {
    if (isset($_COOKIE['powrecommerce-installed'])) {
        global $base_url;
        unset($_COOKIE['powrecommerce-installed']);
        setcookie('powrecommerce-installed', null, -1, '/');
        $response = new RedirectResponse(Url::fromRoute('system.admin_config_content')->toString().'/formats/?powrecommerce-installed');
        $response->send();
    }
}

/**
 * Implements hook_form_alter().
 */
function powrecommerce_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    if (isset($_GET['powrecommerce-installed'])) {
        $form['powrecommerce_config_popup'] = [
            '#theme' => 'powrecommerce_config_popup',
        ];
        $form["#attached"]["library"][] = 'powrecommerce/dialog';
    }
}
