<?php
/**
 * @file
 * Contains powrgraph.module.
 */
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function powrgraph_theme() {
    global $base_url;
    return [
        'powrgraph_config_popup' => [
            'template'  => 'powrgraph_config_popup',
            'render element' => 'dialog'
        ],
    ];
}

function powrgraph_page_top(array &$page_top) {
    if (isset($_COOKIE['powrgraph-installed'])) {
        global $base_url;
        unset($_COOKIE['powrgraph-installed']);
        setcookie('powrgraph-installed', null, -1, '/');
        $response = new RedirectResponse(Url::fromRoute('system.admin_config_content')->toString().'/formats/?powrgraph-installed');
        $response->send();
    }
}

/**
 * Implements hook_form_alter().
 */
function powrgraph_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    if (isset($_GET['powrgraph-installed'])) {
        $form['powrgraph_config_popup'] = [
            '#theme' => 'powrgraph_config_popup',
        ];
        $form["#attached"]["library"][] = 'powrgraph/dialog';
    }
}
