<?php
/**
 * @file
 * Contains powrimageresizer.module.
 */
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function powrimageresizer_theme() {
    global $base_url;
    return [
        'powrimageresizer_config_popup' => [
            'template'  => 'powrimageresizer_config_popup',
            'render element' => 'dialog'
        ],
    ];
}

function powrimageresizer_page_top(array &$page_top) {
    if (isset($_COOKIE['powrimageresizer-installed'])) {
        global $base_url;
        unset($_COOKIE['powrimageresizer-installed']);
        setcookie('powrimageresizer-installed', null, -1, '/');
        $response = new RedirectResponse(Url::fromRoute('system.admin_config_content')->toString().'/formats/?powrimageresizer-installed');
        $response->send();
    }
}

/**
 * Implements hook_form_alter().
 */
function powrimageresizer_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    if (isset($_GET['powrimageresizer-installed'])) {
        $form['powrimageresizer_config_popup'] = [
            '#theme' => 'powrimageresizer_config_popup',
        ];
        $form["#attached"]["library"][] = 'powrimageresizer/dialog';
    }
}
