<?php
/**
 * @file
 * Contains powrmap.module.
 */
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function powrmap_theme() {
    global $base_url;
    return [
        'powrmap_config_popup' => [
            'template'  => 'powrmap_config_popup',
            'render element' => 'dialog'
        ],
    ];
}

function powrmap_page_top(array &$page_top) {
    if (isset($_COOKIE['powrmap-installed'])) {
        global $base_url;
        unset($_COOKIE['powrmap-installed']);
        setcookie('powrmap-installed', null, -1, '/');
        $response = new RedirectResponse(Url::fromRoute('system.admin_config_content')->toString().'/formats/?powrmap-installed');
        $response->send();
    }
}

/**
 * Implements hook_form_alter().
 */
function powrmap_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    if (isset($_GET['powrmap-installed'])) {
        $form['powrmap_config_popup'] = [
            '#theme' => 'powrmap_config_popup',
        ];
        $form["#attached"]["library"][] = 'powrmap/dialog';
    }
}
